global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "Prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "Grafana"
    static_configs:
      - targets: ["localhost:3000"]

  - job_name: 'Docker' 
    static_configs:
      - targets: ['localhost:9323']

  - job_name: 'Node-exporter'
    static_configs:
    - targets: ['localhost:9100']

  - job_name: 'cadvisor-exporter'
    static_configs:
    - targets: ['localhost:9200']