version: '3'

services:
 postgres:
  image: postgres:latest
  restart: always
  volumes:
   - ./data/postgres:/var/lib/postgresql/data
  environment:
   POSTGRES_DB: keycloak
   POSTGRES_USER: keycloak
   POSTGRES_PASSWORD: WJIFji34f

 keycloak:
  image: jboss/keycloak:latest
  restart: always
  ports:
   - '8081:8080'
  environment:
   DB_VENDOR: postgres
   DB_ADDR: postgres
   DB_DATABASE: keycloak
   DB_USER: keycloak
   DB_SCHEMA: public
   DB_PASSWORD: WJIFji34f
   PROXY_ADDRESS_FORWARDING: "true"
  depends_on:
   - postgres