version: '3'

services:

 postgres:
  image: postgres
  restart: always
  volumes:
   - ./data/postgres:/var/lib/postgresql/data
  env_file:
   - .env

 keycloak:
  image: jboss/keycloak:latest
  restart: always
  ports:
   - '8081:8080'
  env_file:
   - .env
  depends_on:
   - postgres
